// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// GPpred_rcpp
Rcpp::List GPpred_rcpp(const Eigen::Map<Eigen::MatrixXd>& K, const Eigen::Map<Eigen::MatrixXd>& Kstar, const Eigen::Map<Eigen::MatrixXd>& Kstarstar, const Eigen::Map<Eigen::VectorXd>& y, bool only_mean);
RcppExport SEXP _GauProMod_GPpred_rcpp(SEXP KSEXP, SEXP KstarSEXP, SEXP KstarstarSEXP, SEXP ySEXP, SEXP only_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Kstar(KstarSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Kstarstar(KstarstarSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type only_mean(only_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(GPpred_rcpp(K, Kstar, Kstarstar, y, only_mean));
    return rcpp_result_gen;
END_RCPP
}
// GPpredmean_rcpp
Rcpp::List GPpredmean_rcpp(const Eigen::Map<Eigen::MatrixXd>& K, const Eigen::Map<Eigen::MatrixXd>& Kstar, const Eigen::Map<Eigen::MatrixXd>& Kstarstar, const Eigen::Map<Eigen::VectorXd>& y, const Eigen::Map<Eigen::MatrixXd>& H, const Eigen::Map<Eigen::MatrixXd>& Hstar, bool only_mean);
RcppExport SEXP _GauProMod_GPpredmean_rcpp(SEXP KSEXP, SEXP KstarSEXP, SEXP KstarstarSEXP, SEXP ySEXP, SEXP HSEXP, SEXP HstarSEXP, SEXP only_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Kstar(KstarSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Kstarstar(KstarstarSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Hstar(HstarSEXP);
    Rcpp::traits::input_parameter< bool >::type only_mean(only_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(GPpredmean_rcpp(K, Kstar, Kstarstar, y, H, Hstar, only_mean));
    return rcpp_result_gen;
END_RCPP
}
// cholupdateL_rcpp
Eigen::MatrixXd cholupdateL_rcpp(const Eigen::Map<Eigen::MatrixXd>& L, const Eigen::Map<Eigen::MatrixXd>& V12, const Eigen::Map<Eigen::MatrixXd>& V22);
RcppExport SEXP _GauProMod_cholupdateL_rcpp(SEXP LSEXP, SEXP V12SEXP, SEXP V22SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type V12(V12SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type V22(V22SEXP);
    rcpp_result_gen = Rcpp::wrap(cholupdateL_rcpp(L, V12, V22));
    return rcpp_result_gen;
END_RCPP
}
// cholfac_rcpp
Eigen::MatrixXd cholfac_rcpp(const Eigen::Map<Eigen::MatrixXd>& A);
RcppExport SEXP _GauProMod_cholfac_rcpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(cholfac_rcpp(A));
    return rcpp_result_gen;
END_RCPP
}
// crossDist_rcpp
Eigen::MatrixXd crossDist_rcpp(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::MatrixXd>& Y, const Rcpp::Nullable<Eigen::Map<Eigen::MatrixXd>>& M);
RcppExport SEXP _GauProMod_crossDist_rcpp(SEXP XSEXP, SEXP YSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Eigen::Map<Eigen::MatrixXd>>& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(crossDist_rcpp(X, Y, M));
    return rcpp_result_gen;
END_RCPP
}
// crossDist_sparse_noloop
Eigen::SparseMatrix<double> crossDist_sparse_noloop(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::MatrixXd>& Y, double rmax, const Rcpp::Nullable<Eigen::Map<Eigen::MatrixXd>>& M);
RcppExport SEXP _GauProMod_crossDist_sparse_noloop(SEXP XSEXP, SEXP YSEXP, SEXP rmaxSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Eigen::Map<Eigen::MatrixXd>>& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(crossDist_sparse_noloop(X, Y, rmax, M));
    return rcpp_result_gen;
END_RCPP
}
// kGaussian_rcpp
Eigen::MatrixXd kGaussian_rcpp(const Eigen::Map<Eigen::MatrixXd> R, double l, double h, int d, const Eigen::Map<Eigen::MatrixXd> W, bool use_symmetry);
RcppExport SEXP _GauProMod_kGaussian_rcpp(SEXP RSEXP, SEXP lSEXP, SEXP hSEXP, SEXP dSEXP, SEXP WSEXP, SEXP use_symmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type use_symmetry(use_symmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(kGaussian_rcpp(R, l, h, d, W, use_symmetry));
    return rcpp_result_gen;
END_RCPP
}
// kMatern_rcpp
Eigen::MatrixXd kMatern_rcpp(const Eigen::Map<Eigen::MatrixXd> R, double l, double h, double v, int d, const Eigen::Map<Eigen::MatrixXd> W, bool use_symmetry);
RcppExport SEXP _GauProMod_kMatern_rcpp(SEXP RSEXP, SEXP lSEXP, SEXP hSEXP, SEXP vSEXP, SEXP dSEXP, SEXP WSEXP, SEXP use_symmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type use_symmetry(use_symmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(kMatern_rcpp(R, l, h, v, d, W, use_symmetry));
    return rcpp_result_gen;
END_RCPP
}
// kTriangular_rcpp
Eigen::MatrixXd kTriangular_rcpp(const Eigen::Map<Eigen::MatrixXd> R, double l, double h, int d, const Eigen::Map<Eigen::MatrixXd> W, bool use_symmetry);
RcppExport SEXP _GauProMod_kTriangular_rcpp(SEXP RSEXP, SEXP lSEXP, SEXP hSEXP, SEXP dSEXP, SEXP WSEXP, SEXP use_symmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type use_symmetry(use_symmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(kTriangular_rcpp(R, l, h, d, W, use_symmetry));
    return rcpp_result_gen;
END_RCPP
}
// kSpherical_rcpp
Eigen::MatrixXd kSpherical_rcpp(const Eigen::Map<Eigen::MatrixXd> R, double l, double h, int d, const Eigen::Map<Eigen::MatrixXd> W, bool use_symmetry);
RcppExport SEXP _GauProMod_kSpherical_rcpp(SEXP RSEXP, SEXP lSEXP, SEXP hSEXP, SEXP dSEXP, SEXP WSEXP, SEXP use_symmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type use_symmetry(use_symmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(kSpherical_rcpp(R, l, h, d, W, use_symmetry));
    return rcpp_result_gen;
END_RCPP
}
// kCauchy_rcpp
Eigen::MatrixXd kCauchy_rcpp(const Eigen::Map<Eigen::MatrixXd> R, double l, double h, double v, int d, const Eigen::Map<Eigen::MatrixXd> W, bool use_symmetry);
RcppExport SEXP _GauProMod_kCauchy_rcpp(SEXP RSEXP, SEXP lSEXP, SEXP hSEXP, SEXP vSEXP, SEXP dSEXP, SEXP WSEXP, SEXP use_symmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type use_symmetry(use_symmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(kCauchy_rcpp(R, l, h, v, d, W, use_symmetry));
    return rcpp_result_gen;
END_RCPP
}
// kLinear_rcpp
Eigen::MatrixXd kLinear_rcpp(const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::MatrixXd> Y, double h, double c, int d, const Eigen::Map<Eigen::MatrixXd> W, bool use_symmetry);
RcppExport SEXP _GauProMod_kLinear_rcpp(SEXP XSEXP, SEXP YSEXP, SEXP hSEXP, SEXP cSEXP, SEXP dSEXP, SEXP WSEXP, SEXP use_symmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type use_symmetry(use_symmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(kLinear_rcpp(X, Y, h, c, d, W, use_symmetry));
    return rcpp_result_gen;
END_RCPP
}
// kPolynomial_rcpp
Eigen::MatrixXd kPolynomial_rcpp(const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::MatrixXd> Y, double h, int degree, double c, int d, const Eigen::Map<Eigen::MatrixXd> W, bool use_symmetry);
RcppExport SEXP _GauProMod_kPolynomial_rcpp(SEXP XSEXP, SEXP YSEXP, SEXP hSEXP, SEXP degreeSEXP, SEXP cSEXP, SEXP dSEXP, SEXP WSEXP, SEXP use_symmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    Rcpp::traits::input_parameter< bool >::type use_symmetry(use_symmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(kPolynomial_rcpp(X, Y, h, degree, c, d, W, use_symmetry));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GauProMod_GPpred_rcpp", (DL_FUNC) &_GauProMod_GPpred_rcpp, 5},
    {"_GauProMod_GPpredmean_rcpp", (DL_FUNC) &_GauProMod_GPpredmean_rcpp, 7},
    {"_GauProMod_cholupdateL_rcpp", (DL_FUNC) &_GauProMod_cholupdateL_rcpp, 3},
    {"_GauProMod_cholfac_rcpp", (DL_FUNC) &_GauProMod_cholfac_rcpp, 1},
    {"_GauProMod_crossDist_rcpp", (DL_FUNC) &_GauProMod_crossDist_rcpp, 3},
    {"_GauProMod_crossDist_sparse_noloop", (DL_FUNC) &_GauProMod_crossDist_sparse_noloop, 4},
    {"_GauProMod_kGaussian_rcpp", (DL_FUNC) &_GauProMod_kGaussian_rcpp, 6},
    {"_GauProMod_kMatern_rcpp", (DL_FUNC) &_GauProMod_kMatern_rcpp, 7},
    {"_GauProMod_kTriangular_rcpp", (DL_FUNC) &_GauProMod_kTriangular_rcpp, 6},
    {"_GauProMod_kSpherical_rcpp", (DL_FUNC) &_GauProMod_kSpherical_rcpp, 6},
    {"_GauProMod_kCauchy_rcpp", (DL_FUNC) &_GauProMod_kCauchy_rcpp, 7},
    {"_GauProMod_kLinear_rcpp", (DL_FUNC) &_GauProMod_kLinear_rcpp, 7},
    {"_GauProMod_kPolynomial_rcpp", (DL_FUNC) &_GauProMod_kPolynomial_rcpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_GauProMod(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
