# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GPpred_rcpp <- function(K, Kstar, Kstarstar, y) {
    .Call('GauProMod_GPpred_rcpp', PACKAGE = 'GauProMod', K, Kstar, Kstarstar, y)
}

GPpredmean_rcpp <- function(K, Kstar, Kstarstar, y, H, Hstar) {
    .Call('GauProMod_GPpredmean_rcpp', PACKAGE = 'GauProMod', K, Kstar, Kstarstar, y, H, Hstar)
}

cholupdateL_rcpp <- function(L, V12, V22) {
    .Call('GauProMod_cholupdateL_rcpp', PACKAGE = 'GauProMod', L, V12, V22)
}

