# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GPpred_rcpp <- function(K, Kstar, Kstarstar, y, only_mean = FALSE) {
    .Call('_GauProMod_GPpred_rcpp', PACKAGE = 'GauProMod', K, Kstar, Kstarstar, y, only_mean)
}

GPpredmean_rcpp <- function(K, Kstar, Kstarstar, y, H, Hstar, only_mean = FALSE) {
    .Call('_GauProMod_GPpredmean_rcpp', PACKAGE = 'GauProMod', K, Kstar, Kstarstar, y, H, Hstar, only_mean)
}

#' Cross-distance between two matrices (RcppEigen version)
NULL

cholupdateL_rcpp <- function(L, V12, V22) {
    .Call('_GauProMod_cholupdateL_rcpp', PACKAGE = 'GauProMod', L, V12, V22)
}

cholfac_rcpp <- function(A) {
    .Call('_GauProMod_cholfac_rcpp', PACKAGE = 'GauProMod', A)
}

crossDist_rcpp <- function(X, Y, M = NULL) {
    .Call('_GauProMod_crossDist_rcpp', PACKAGE = 'GauProMod', X, Y, M)
}

